package com.employee.util.constants;

public interface EmployeeJDBCTemplateSQLConstant {

	String INSERT_EMP_DETAILS = "INSERT INTO EMPLOYEE (ID, EMAIL, FIRSTNAME, LASTNAME, USERCREATED)  VALUES (?,?,?,?,?)";
	String UPDATE_EMP_DETAILS = "UPDATE EMPLOYEE SET EMAIL = ?, FIRSTNAME = ?, LASTNAME = ?, USERCREATED = ?, PHOTO = ? WHERE ID = ?";
	String SELECT_ALL_EMP = "SELECT * FROM EMPLOYEE";

	String SELECT_EMP_BY_USER = "SELECT * FROM EMPLOYEE WHERE USERCREATED = ?";
	String SELECT_EMP_BY_ID = "SELECT * FROM EMPLOYEE WHERE ID = ?";
	
	String DELETE_EMP_BY_ID = "DELETE FROM EMPLOYEE WHERE ID = ?";
}
